services:
  cloudflare-ddns:
    image: dani01cs/cloudflare_ddns_updater:latest
    container_name: cloudflare-ddns
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    ports:
      - "5000:5000"
    volumes:
      - ${CONFIG_FILE}:/config.json
    environment:
      CONFIG_PATH: /
      FLASK_SECRET: ${FLASK_SECRET:-please-change-me}
